version: "3.8"
services: 
    nats:
        image: nats-streaming
        command: ['-p', '4222', '-m', '8222', '-hbi', '5s', '-hbt', '5s', '-hbf', '2', '-SD', '-cid', 'ticketing']
        ports: 
            - "4222:4222"
            - "8222:8222"

